algoritmo "AreaQuadrado"
var
n1,n2,r:real
inicio
escreval("------------------------------------------------------------------")
escreval("==================================================================")
escreval("ÁREA QUADRADA DO RETANGULO")
escreval("==================================================================")
escreval("------------------------------------------------------------------")
escreval("Valor da BASE: ")
leia(n1)
escreval("Valor da ALTURA: ")
LEIA(N2)
r<-n1*n2
escreval("A área da quadrado é de: ", r)
escreval("------------------------------------------------------------------")
fimalgoritmo